logger:
  level: info
  output: stdout

# storage:
#   location: file
#   params:
#     root: /path/to/folder

storage:
  location: dropbox
  params:
    root: Downloads
    session:
      - xxxxxxx
      - yyyyyyyy
      - true
      - zzzzzzzzzzzzzz
      - aaaaaaaaaaaaaa
      - false
      - :dropbox

